In [2]:
# df.to_csv("clean_laptop_data_csv")

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("laptopPrice.csv")

In [5]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [6]:
df.duplicated().sum()

np.int64(21)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
df.dropna()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [11]:
df.drop(['os','os_bit','weight','msoffice','rating','Number of Ratings','Number of Reviews'],axis=1,inplace=True)

In [12]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [13]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [14]:
brand_dict={'ASUS':1, 'Lenovo':2, 'acer':3, 'Avita':4, 'HP':5, 'DELL':6, 'MSI':7, 'APPLE':8}

In [15]:
df['brand']=df['brand'].map(brand_dict)

In [16]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [17]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [18]:
proc_brand_dict={'Intel':1, 'AMD':2, 'M1':3}

In [19]:
df['processor_brand']=df['processor_brand'].map(proc_brand_dict)

In [20]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [21]:
df['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [22]:
proc_name_dict={'Core i3':1, 'Core i5':2, 'Celeron Dual':3, 'Ryzen 5':4, 'Core i7':5,
       'Core i9':6, 'M1':7, 'Pentium Quad':8, 'Ryzen 3':9, 'Ryzen 7':10, 'Ryzen 9':11}

In [23]:
df['processor_name']=df['processor_name'].map(proc_name_dict)

In [24]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [25]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [26]:
proc_gen_dict={'10th':1, 'Not Available':2, '11th':3, '7th':4, '8th':5, '9th':6, '4th':7,
       '12th':8}

In [27]:
df['processor_gnrtn']=df['processor_gnrtn'].map(proc_gen_dict)

In [28]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [29]:
df.dtypes

brand               int64
processor_brand     int64
processor_name      int64
processor_gnrtn     int64
ram_gb             object
ram_type           object
ssd                object
hdd                object
graphic_card_gb    object
warranty           object
Touchscreen        object
Price               int64
dtype: object

In [30]:
df['ram_gb'].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [31]:
ram_gb_dict={'4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32}

In [32]:
df['ram_gb']=df['ram_gb'].map(ram_gb_dict)

In [33]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [34]:
df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [35]:
ram_type_dict={'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6}

In [36]:
df['ram_type']=df['ram_type'].map(ram_type_dict)

In [37]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4,1,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4,1,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8,1,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4,1,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4,1,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4,1,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4,1,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8,1,512 GB,0 GB,0 GB,No warranty,No,57490

In [38]:
df['ssd'].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [39]:
ssd_dict={'0 GB':0, '512 GB':512,'256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048,
       '3072 GB':3072}

In [40]:
df['ssd']=df['ssd'].map(ssd_dict)

In [41]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4,1,0,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4,1,0,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8,1,512,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4,1,0,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4,1,1024,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4,1,1024,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4,1,1024,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8,1,512,0 GB,0 GB,No warranty,No,57490

In [42]:
df['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [43]:
hdd_dict={'1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048}

In [44]:
df['hdd']=df['hdd'].map(hdd_dict)

In [45]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0 GB,No warranty,No,34649
1,2,1,1,1,4,1,0,1024,0 GB,No warranty,No,38999
2,2,1,1,1,4,1,0,1024,0 GB,No warranty,No,39999
3,1,1,2,1,8,1,512,0,2 GB,No warranty,No,69990
4,1,1,3,2,4,1,0,512,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0 GB,1 year,No,135990
819,1,2,11,2,4,1,1024,0,0 GB,1 year,No,144990
820,1,2,11,2,4,1,1024,0,4 GB,1 year,No,149990
821,1,2,11,2,4,1,1024,0,4 GB,1 year,No,142990
822,2,2,4,1,8,1,512,0,0 GB,No warranty,No,57490

In [46]:
df['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [47]:
graphic_card_dict={'0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8}

In [48]:
df['graphic_card_gb']=df['graphic_card_gb'].map(graphic_card_dict)

In [49]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0,No warranty,No,34649
1,2,1,1,1,4,1,0,1024,0,No warranty,No,38999
2,2,1,1,1,4,1,0,1024,0,No warranty,No,39999
3,1,1,2,1,8,1,512,0,2,No warranty,No,69990
4,1,1,3,2,4,1,0,512,0,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,1 year,No,135990
819,1,2,11,2,4,1,1024,0,0,1 year,No,144990
820,1,2,11,2,4,1,1024,0,4,1 year,No,149990
821,1,2,11,2,4,1,1024,0,4,1 year,No,142990
822,2,2,4,1,8,1,512,0,0,No warranty,No,57490

In [50]:
df['warranty'].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [51]:
warranty_dict={'No warranty':1, '1 year':2, '2 years':3, '3 years':4}

In [52]:
df['warranty']=df['warranty'].map(warranty_dict)

In [53]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0,1,No,34649
1,2,1,1,1,4,1,0,1024,0,1,No,38999
2,2,1,1,1,4,1,0,1024,0,1,No,39999
3,1,1,2,1,8,1,512,0,2,1,No,69990
4,1,1,3,2,4,1,0,512,0,1,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,2,No,135990
819,1,2,11,2,4,1,1024,0,0,2,No,144990
820,1,2,11,2,4,1,1024,0,4,2,No,149990
821,1,2,11,2,4,1,1024,0,4,2,No,142990
822,2,2,4,1,8,1,512,0,0,1,No,57490

In [54]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [55]:
touchscreen_dict={'No':1, 'Yes':2}

In [56]:
df['Touchscreen']=df['Touchscreen'].map(touchscreen_dict)

In [57]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0,1,1,34649
1,2,1,1,1,4,1,0,1024,0,1,1,38999
2,2,1,1,1,4,1,0,1024,0,1,1,39999
3,1,1,2,1,8,1,512,0,2,1,1,69990
4,1,1,3,2,4,1,0,512,0,1,1,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,2,1,135990
819,1,2,11,2,4,1,1024,0,0,2,1,144990
820,1,2,11,2,4,1,1024,0,4,2,1,149990
821,1,2,11,2,4,1,1024,0,4,2,1,142990
822,2,2,4,1,8,1,512,0,0,1,1,57490

In [58]:
x=df.drop('Price', axis=1)
y=df['Price']

In [59]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen
0,1,1,1,1,4,1,0,1024,0,1,1
1,2,1,1,1,4,1,0,1024,0,1,1
2,2,1,1,1,4,1,0,1024,0,1,1
3,1,1,2,1,8,1,512,0,2,1,1
4,1,1,3,2,4,1,0,512,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,2,1
819,1,2,11,2,4,1,1024,0,0,2,1
820,1,2,11,2,4,1,1024,0,4,2,1
821,1,2,11,2,4,1,1024,0,4,2,1
822,2,2,4,1,8,1,512,0,0,1,1

In [60]:
y

0       34649
1       38999
2       39999
3       69990
4       26990
        ...
818    135990
819    144990
820    149990
821    142990
822     57490
Name: Price, Length: 802, dtype: int64

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test=train_test_split(x,y,random_state=42, test_size=0.4 )

In [62]:
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen
780,3,2,10,2,4,1,1024,0,4,2,1
261,1,1,2,1,8,1,512,0,4,2,1
366,2,1,2,3,8,1,512,0,0,2,2
488,2,1,5,1,8,1,512,0,4,2,1
16,5,1,2,3,8,1,256,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
73,2,1,1,1,4,1,256,0,0,1,1
108,6,1,1,3,8,1,512,0,0,2,2
275,2,1,2,1,8,1,512,0,2,2,1
445,1,1,2,3,8,1,256,1024,0,2,1
104,1,1,1,3,8,1,512,0,0,2,1

In [63]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen
196,3,1,2,2,8,4,0,512,4,1,1
299,1,1,2,3,8,3,512,0,0,2,1
171,6,1,1,1,8,1,256,1024,0,2,1
537,5,1,5,1,16,1,1024,0,6,2,1
551,7,1,5,3,16,1,1024,0,8,3,1
...,...,...,...,...,...,...,...,...,...,...,...
181,6,1,1,3,4,1,256,1024,0,2,1
548,5,1,5,3,16,1,1024,0,4,1,1
557,1,1,5,1,16,1,1024,0,8,1,1
180,1,1,1,1,4,1,256,1024,0,1,1
665,6,2,4,2,8,1,256,0,0,2,1

In [64]:
y_train

780    99990
261    63990
366    82990
488    68990
16     65390
       ...
73     41990
108    60790
275    57500
445    52990
104    44990
Name: Price, Length: 481, dtype: int64

In [65]:
y_test

196     50990
299     72990
171     41490
537    144690
551    129990
        ...
181     43990
548    121990
557    234990
180     40990
665     44490
Name: Price, Length: 321, dtype: int64

In [66]:
x_test.shape,y_test.shape,x_train.shape,y_train.shape

((321, 11), (321,), (481, 11), (481,))

In [67]:
from sklearn.linear_model import LinearRegression

In [68]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [69]:
lr.score(x_test,y_test)

0.6016748540629289

In [70]:
lr.score(x_train,y_train)

0.6297857702159584

In [71]:
pred=lr.predict(x_test)

In [72]:
pred

array([ 85501.52554829,  72611.16549968,  59048.37567727, 145869.69718315,
       157360.96831434, 147709.81883548,  89887.71897214,  97009.75294767,
        51692.00889399,  73059.52789248,  27824.95264204,  48415.48479221,
        75353.18962712,  89760.76200463,  66348.48067331,  82992.17488088,
        79852.53531215,  60865.50329503,  62303.12893772, 155386.31615967,
        35341.68916228,  23744.71503393,  71840.69502326,  51101.28967283,
        34355.83507766,  40331.15691837,  73996.43155614, 149977.46830136,
        41768.78256107,  29776.98722737,  54629.89756395,  52542.95601104,
        59474.68446595,  56871.66351008,  54424.4757932 ,  27824.95264204,
       120096.82179079,  64458.86547059,  55538.22316249,  94495.92997334,
        26547.69673631,  98320.49697875,  71685.69635725,  34609.96012994,
        78482.6021641 ,  39390.43918705, 133931.17015426,  62444.41150264,
       105482.79028051, 102177.69763843, 132886.37140982,  92956.04975509,
        69124.23083598,  89490.77333437,  72267.00381194, 163789.08435953,
       102679.80857812,  59339.77749837,  66661.04040718, 133918.472227  ,
        92676.19059083,  46298.38620092,  39700.2135603 ,  72044.3969708 ,
        91613.44610569,  75273.68746186, 147397.09344012,  38379.12233303,
        39700.2135603 ,  55398.10944223, 130616.4870818 , 153867.73705142,
        68273.28371894,  89760.76200463,  38379.12233303,  36427.0877477 ,
       112697.95258823,  94707.72734143,  51692.00889399,  56376.51037853,
        37438.40460172,  49915.52981753,  74982.28564076,  27824.95264204,
        34355.83507766,  62060.43039814,  88998.26023291, 106123.02827896,
        54494.99059638, 147709.81883548,  77225.7220472 ,  54068.6818077 ,
        90564.26309345,  77877.88315748,  70092.18010702, 104148.37612429,
       138868.43524309,  75353.18962712,  41648.20745012,  63154.07605477,
        74925.15300958,  40755.79524674, 120491.58084588,  63877.5580159 ,
        81497.29691506,  92676.19059083,  66046.82837142,  82992.17488088,
        29350.6784387 ,  88351.0150634 ,  80256.22653149,  90701.47973595,
        60351.09435239,  72267.00381194,  53819.5989882 ,  60486.00131996,
        51105.33036834,  65292.57138637,  63828.85473438,  51531.63915702,
       146617.55009023,  69665.78699882,  51692.00889399,  80243.11288242,
        61415.19586377,  58540.34233197,  39700.2135603 ,  74488.67805963,
       161143.43964313,  62188.32368281,  60351.09435239,  52969.26479972,
       114635.47708987, 198987.59576156,  39230.06945008,  73252.85789656,
       138779.50913201, 118949.86795513,  77155.20724402,  76339.04371175,
       174532.50258364,  61772.63618559,  72044.3969708 ,  49196.48108755,
        65106.11064011, 154425.68843158,  47961.82477188,  63286.65027056,
        71436.77133613,  89638.79395102,  60351.09435239,  89760.76200463,
        52116.64722236,  27533.55082094,  72838.21145667, 143403.25365517,
        90564.26309345,  77877.88315748,  60486.00131996,  80420.12666574,
        83142.1564769 ,  50725.82839328, 107158.25629131,  60689.7032675 ,
        73637.73094259,  90564.26309345,  76440.71264497,  25021.97093965,
        25581.5162356 ,  65106.11064011,  90220.10140571,  73030.25105542,
        37997.94989766,  70449.87619418, 112830.07915202,  22778.53453322,
        87916.34425619,  58533.17953326, 104148.37612429,  32830.109281  ,
        32237.4529116 ,  31888.03452344,  62232.61413454, 146296.00597183,
       105090.15264634,  89887.71897214,  81379.93156911, 154068.82881658,
        29350.6784387 , 260335.59575908,  54494.99059638,  63218.46821917,
        90220.10140571,  74096.02302712, 143242.8839182 ,  65829.59260124,
        62641.73785283,  37438.40460172, 194135.01792376,  51531.63915702,
        67058.14522544,  48069.5676579 ,  49915.52981753,  75069.98551432,
       102253.49978944,  29911.89419495,  29776.98722737,  54494.99059638,
        43943.82426794,  35149.83184197,  32830.109281  ,  66842.12478538,
        82434.5806337 ,  47961.82477188,  58463.45193145,  38938.66762898,
        31207.69718651,  46746.80597033,  31207.69718651,  45760.9518857 ,
        70449.87619418,  42702.58460883,  72267.00381194, 131467.43419885,
        77865.18523021,  22778.53453322,  37997.94989766,  49080.88451192,
        24730.56911855,  88749.44515061,  21173.59244219, 131123.27251111,
        73536.06200937,  70496.05360481,  32830.109281  ,  80420.12666574,
        75414.14720206,  25581.5162356 , 112697.95258823,  80108.20591484,
        90564.26309345,  82371.33842636,  93125.20284269,  42418.09847129,
        64575.61788798, 125470.25777407, 142907.05540688, 110527.70597166,
        81271.07378279,  39230.06945008,  52472.44120786,  60865.50329503,
        81314.45841389,  39110.85136538,  54494.99059638,  72448.08819014,
        64031.94375335,  35149.83184197,  54494.99059638,  80256.22653149,
        78304.19194615,  26974.00552499,  90564.26309345,  58540.34233197,
       120593.10435861, 104459.80484756,  54494.99059638,  90564.26309345,
        31586.46654107,  97593.40117891,  60492.3769173 ,  51209.51566345,
        34355.83507766,  74783.16756282,  81945.02963768,  60486.00131996,
        48069.5676579 ,  56447.02518171,  74306.90258107,  54068.6818077 ,
        92956.04975509,  71685.69635725,  66392.74550574,  71840.69502326,
        73245.07591007, 128710.04088182,  47643.25886922, 138487.86763048,
        73059.52789248,  34609.96012994, 101175.38313718,  91613.44610569,
        62060.43039814,  37585.12556872, 141290.84933286,  88560.32405206,
        62142.75920075,  65887.75828409,  86985.89497388,  53057.36495368,
        50553.32254023,  89552.94623943,  49062.91224017,  60492.3769173 ,
        83223.10836812,  66987.63042226, 106123.02827896, 128983.97269945,
        55328.69651215, 139135.11279999,  34355.83507766,  23744.71503393,
        31207.69718651,  95244.69865557,  61637.72921802, 146706.84387958,
        48069.5676579 , 139135.11279999, 150828.4154184 ,  40686.06764492,
        58533.17953326])

In [73]:
y_test

196     50990
299     72990
171     41490
537    144690
551    129990
        ...
181     43990
548    121990
557    234990
180     40990
665     44490
Name: Price, Length: 321, dtype: int64