In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('Bikes.csv')

In [7]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [8]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [9]:
df.tail(8)

,bike_name,price,city,kms_driven,owner,age,power,brand
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [10]:
df.head(6)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

In [12]:
df.describe()

              price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [13]:
df.dtypes

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [14]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [15]:
df.duplicated().sum()

np.int64(25324)

In [16]:
df.isnull()

       bike_name  price   city  kms_driven  owner    age  power  brand
0          False  False  False       False  False  False  False  False
1          False  False  False       False  False  False  False  False
2          False  False  False       False  False  False  False  False
3          False  False  False       False  False  False  False  False
4          False  False  False       False  False  False  False  False
...          ...    ...    ...         ...    ...    ...    ...    ...
32643      False  False  False       False  False  False  False  False
32644      False  False  False       False  False  False  False  False
32645      False  False  False       False  False  False  False  False
32646      False  False  False       False  False  False  False  False
32647      False  False  False       False  False  False  False  False

[32648 rows x 8 columns]

In [17]:
df.drop_duplicates(inplace = True)  #INPLACE == 'True'

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.dropna()         #remove null values from data set

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [20]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [21]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [22]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [23]:
df.dtypes

price         float64
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [24]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [25]:
owner_dict={'First Owner':1,'Second Owner':2,'Third Owner':3,'Fourth Owner Or More':4}

In [26]:
df['owner']=df['owner'].map(owner_dict)

In [27]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [28]:
cat_col=df.select_dtypes(include='object')

In [29]:
cat_col

                brand
0                 TVS
1       Royal Enfield
2             Triumph
3                 TVS
4              Yamaha
...               ...
9362             Hero
9369            Bajaj
9370  Harley-Davidson
9371            Bajaj
9372            Bajaj

[7324 rows x 1 columns]

In [30]:
num_col=df.select_dtypes(exclude='object')

In [31]:
num_col

         price  kms_driven  owner  age  power
0      35000.0     17654.0      1  3.0  110.0
1     119900.0     11000.0      1  4.0  350.0
2     600000.0       110.0      1  8.0  675.0
3      65000.0     16329.0      1  4.0  180.0
4      80000.0     10000.0      1  3.0  150.0
...        ...         ...    ...  ...    ...
9362   25000.0     48587.0      1  8.0  150.0
9369   35000.0     60000.0      1  9.0  220.0
9370  450000.0      3430.0      1  4.0  750.0
9371  139000.0     21300.0      1  4.0  400.0
9372   80000.0      7127.0      1  5.0  220.0

[7324 rows x 5 columns]

In [32]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [33]:
brand_dict={'TVS':1, 'Royal Enfield':2, 'Triumph':3, 'Yamaha':4, 'Honda':5, 'Hero':6,
       'Bajaj':7, 'Suzuki':8, 'Benelli':9, 'KTM':10, 'Mahindra':11, 'Kawasaki':12,
       'Ducati':13, 'Hyosung':14, 'Harley-Davidson':15, 'Jawa':16, 'BMW':17, 'Indian':18,
       'Rajdoot':19, 'LML':20, 'Yezdi':21, 'MV':22, 'Ideal':23}

In [34]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

Random Forest classifier Algorithm

In [35]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
from sklearn.datasets import load_breast_cancer
x,y = load_breast_cancer(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [36]:
rfc.score(x_test,y_test)

0.9649122807017544

In [37]:
rfc.predict(x_test)

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [38]:
x_train

array([[9.029e+00, 1.733e+01, 5.879e+01, ..., 1.750e-01, 4.228e-01,
        1.175e-01],
       [2.109e+01, 2.657e+01, 1.427e+02, ..., 2.903e-01, 4.098e-01,
        1.284e-01],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]], shape=(455, 30))

In [39]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

Random Forest Regressor Algorithm

In [40]:
from sklearn.ensemble import RandomForestRegressor
rfc = RandomForestRegressor()
from sklearn.datasets import load_breast_cancer
x,y = load_breast_cancer(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
rfc.fit(x_train, y_train)

RandomForestRegressor()

In [41]:
rfc.score(x_test,y_test)

0.8469756305273501

In [42]:
rfc.predict(x_test)

array([1.  , 0.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.09, 0.25, 0.91, 0.87,
       0.02, 0.94, 0.16, 0.99, 0.  , 0.91, 1.  , 1.  , 0.  , 0.91, 1.  ,
       0.  , 0.99, 1.  , 1.  , 1.  , 0.84, 1.  , 0.  , 0.99, 1.  , 0.6 ,
       0.97, 1.  , 1.  , 0.27, 1.  , 0.  , 0.97, 1.  , 0.  , 1.  , 1.  ,
       0.7 , 0.99, 0.82, 0.91, 1.  , 1.  , 0.  , 0.  , 0.88, 0.97, 1.  ,
       0.97, 1.  , 0.  , 0.15, 1.  , 1.  , 0.  , 0.01, 0.94, 0.99, 0.96,
       0.  , 0.  , 1.  , 0.98, 0.05, 0.  , 1.  , 0.  , 0.99, 0.98, 0.98,
       0.77, 1.  , 0.94, 0.02, 1.  , 0.94, 0.  , 0.14, 0.  , 0.03, 0.01,
       0.99, 1.  , 1.  , 0.75, 0.78, 0.96, 1.  , 1.  , 0.  , 0.  , 1.  ,
       0.  , 0.04, 1.  , 0.  , 0.  , 0.99, 1.  , 1.  , 0.  , 0.28, 0.79,
       0.01, 1.  , 0.86, 0.  ])

In [43]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])